apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influx-icetruck
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData: {version: Flux, organization: team13, defaultBucket: icetruck}
    secureJsonData: {token: "${INFLUX_TOKEN}"}
